#include "ORIGEM2.h"

void desalocarTexturas(Jogo *jogo) {
	SDL_DestroyTexture(jogo->acil);
	SDL_DestroyTexture(jogo->blocos[0]);
	SDL_DestroyTexture(jogo->blocos[1]);
	SDL_DestroyTexture(jogo->blocos[2]);
	SDL_DestroyTexture(jogo->blocos[3]);
	SDL_DestroyTexture(jogo->blocos[4]);
	SDL_DestroyTexture(jogo->bolinha);
	SDL_DestroyTexture(jogo->bolinha2);
	SDL_DestroyTexture(jogo->cabeca);
	SDL_DestroyTexture(jogo->cariotipomacho);
	SDL_DestroyTexture(jogo->cariotipofemea);
	SDL_DestroyTexture(jogo->Celula);
	SDL_DestroyTexture(jogo->Cromatinagenelaranja);
	SDL_DestroyTexture(jogo->Cromatinagenepreto);
	SDL_DestroyTexture(jogo->das);
	SDL_DestroyTexture(jogo->embriao);
	SDL_DestroyTexture(jogo->fundonucleo);
	SDL_DestroyTexture(jogo->FundoPolitecnico2);
	SDL_DestroyTexture(jogo->interrogacao);
	SDL_DestroyTexture(jogo->interrogacao2);
	SDL_DestroyTexture(jogo->inventario);
	SDL_DestroyTexture(jogo->iris);
	SDL_DestroyTexture(jogo->iriscabeca);
	SDL_DestroyTexture(jogo->iriscafe);
	SDL_DestroyTexture(jogo->irisfeliz);
	SDL_DestroyTexture(jogo->irismuitofeliz);
	SDL_DestroyTexture(jogo->irismuitotriste);
	SDL_DestroyTexture(jogo->irispensandogato);
	SDL_DestroyTexture(jogo->irisquarto);
	SDL_DestroyTexture(jogo->irissurpresa);
	SDL_DestroyTexture(jogo->iristriste);
	SDL_DestroyTexture(jogo->lixo);
	SDL_DestroyTexture(jogo->met);
	SDL_DestroyTexture(jogo->nucleossomo);
	SDL_DestroyTexture(jogo->oculos);
	SDL_DestroyTexture(jogo->oculosiris);
	SDL_DestroyTexture(jogo->paredecelula);
	SDL_DestroyTexture(jogo->pensamentogato);
	SDL_DestroyTexture(jogo->pocao1);
	SDL_DestroyTexture(jogo->politecnico);
	SDL_DestroyTexture(jogo->quadro);
	SDL_DestroyTexture(jogo->rato);
	SDL_DestroyTexture(jogo->RNA1);
	SDL_DestroyTexture(jogo->RNA2);
	SDL_DestroyTexture(jogo->tetocelula);
}